### ISSUE TITLE
Concurrency Model link broken

### ISSUE THREAD

**Issue by kegbuna** [programmingthomas/FAQ#3]
The link for concurrency model (https://developer.apple.com/library/ios/documentation/cocoa/Conceptual/CoreData/Articles/cdConcurrency.html) returns 404.

**Comment by kegbuna** [comment]
I have found this link on the developer site, maybe this is it: https://developer.apple.com/library/ios/documentation/General/Conceptual/ConcurrencyProgrammingGuide/ConcurrencyandApplicationDesign/ConcurrencyandApplicationDesign.html#//apple_ref/doc/uid/TP40008091-CH100-SW1

**Comment by programmingthomas** [comment]
[This](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Conceptual/CoreData/Concurrency.html) appears to be the most recent link on the subject. I will update the repo.
